version: "3.8"

services:
  app:
    build: .
    ports:
      - "3011:3011"
    volumes:
      - ./data:/app/data
      - ./src:/app/src
    env_file: .env
    environment:
      - MONGODB_URI=mongodb://mongo:27017/mongo-vault
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:4.4.18
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
